import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import FooterSection from "@/components/layout/footer";

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${archivo.variable} font-sans antialiased`}>
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
